Update glycosylator_GUI.py
 fix the 
print "Error while connecting to the database " + filename
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Error while connecting to the database " + filename)?